---
title: "bimm143_lecture06"
author: "Fangchao He"
date: "4/30/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
fna.data <- "WisconsinCancer.csv"
wisc.df <- read.csv(fna.data)
wisc.data <- as.matrix(wisc.df[, 3:32])
row.names(wisc.data) <- wisc.df$id
```

```{r}
diagnosis <- as.numeric(wisc.df$diagnosis == "M")
```

```{r}
colMeans(wisc.data)

apply(wisc.data,2,sd)
```

```{r}
wisc.pr <- prcomp(wisc.data, scale = TRUE)
plot(wisc.pr$x[,1], wisc.pr$x[,2], col = diagnosis + 1)
```


```{r}
pr.var <- wisc.pr$sdev^2
head(pr.var)
```

```{r}
pve <- (pr.var / sum(pr.var))*100
head(pve)
```

```{r}
par(mfcol = c(1,2))
plot(pve, xlab = "Principal Component", 
     ylab = "Proportion of Variance Explained", 
     ylim = c(0, 100), type = "o")
plot(cumsum(pve), xlab = "Principal Component", 
     ylab = "Cumulative Proportion of Variance Explained", 
     ylim = c(0, 100), type = "o")
```

```{r}
data.scaled <- scale(wisc.data)
data.dist <- dist(data.scaled)
wisc.hclust <- hclust(data.dist, method = "complete")
plot(wisc.hclust)
abline(h = 18, col="red", lty=2)
```

```{r}
wisc.hclust.clusters <- cutree(tree = wisc.hclust, k = 4)
table(wisc.hclust.clusters)


```

```{r}
table(wisc.hclust.clusters, diagnosis)
```

```{r}
wisc.pca.hclust <- hclust(dist(wisc.pr$x[,1:7]), method = "ward.D2")
plot(wisc.pca.hclust)
```

```{r}
grps <- cutree(wisc.pca.hclust, k=2)
table(grps)
```

```{r}
plot(wisc.pr$x[,1:2], col=grps)
```

```{r}
#install.packages("rgl")
library(rgl)
plot3d(wisc.pr$x[,1:3], xlab="PC 1", ylab="PC 2", zlab="PC 3", cex=1.5, size=1, type="s", col=diagnosis+1)
```